-- ===========================================================================
-- IMPI SafetyFile Pro — 0001 schema
-- Phase 1 (staff-only UI). The `client` role and client-scoped columns exist
-- now so Phase 2 (client login) needs no schema rebuild. See DECISIONS.md.
-- ===========================================================================

create extension if not exists "pgcrypto";

-- --- Enums -----------------------------------------------------------------
create type user_role            as enum ('staff', 'client');
create type source_type          as enum ('generated', 'evidence');
create type audit_status         as enum ('in_progress', 'complete');
create type audit_result_status  as enum ('compliant', 'partial', 'non_compliant', 'not_applicable');
create type evidence_status      as enum ('pending_review', 'accepted', 'rejected');
create type generated_status     as enum ('draft', 'final');

-- --- Clients -------------------------------------------------------------
create table clients (
  id               uuid primary key default gen_random_uuid(),
  company_name     text not null,
  logo_url         text,
  address          text,
  contact_person   text,
  contact_email    text,
  contact_phone    text,
  registration_no  text,
  client_code      text unique,                 -- auto-generated by trigger if null; admin-editable
  created_at       timestamptz not null default now()
);

-- --- Profiles (1:1 with auth.users) -----------------------------------
create table profiles (
  id          uuid primary key references auth.users(id) on delete cascade,
  role        user_role not null default 'staff',
  full_name   text,
  phone       text,
  client_id   uuid references clients(id) on delete set null,  -- set for Phase-2 client users
  created_at  timestamptz not null default now()
);

-- --- Sector / trade taxonomy (admin-managed, NOT a code enum) ---------
create table sectors (
  id          uuid primary key default gen_random_uuid(),
  name        text not null unique,
  description text,
  active      boolean not null default true,
  created_at  timestamptz not null default now()
);

create table client_sectors (
  client_id uuid not null references clients(id) on delete cascade,
  sector_id uuid not null references sectors(id) on delete cascade,
  primary key (client_id, sector_id)
);

-- --- Document type catalogue -----------------------------------------
create table document_templates (
  id                   uuid primary key default gen_random_uuid(),
  name                 text not null,
  type_code            text not null unique,      -- 'RA','MS','AUD','EVD',... used in numbering
  source_type          source_type not null,
  questionnaire_schema jsonb not null default '[]'::jsonb,  -- array of field defs; see DECISIONS.md item 6
  description          text,
  active               boolean not null default true,
  created_at           timestamptz not null default now()
);

create table document_template_sectors (
  document_template_id uuid not null references document_templates(id) on delete cascade,
  sector_id            uuid not null references sectors(id) on delete cascade,
  primary key (document_template_id, sector_id)
);

-- --- Checklists ------------------------------------------------------
create table checklists (
  id          uuid primary key default gen_random_uuid(),
  sector_id   uuid not null references sectors(id) on delete restrict,
  name        text not null,
  description text,
  version     text not null default '1.0',
  active      boolean not null default true,
  created_at  timestamptz not null default now()
);

create table checklist_items (
  id                        uuid primary key default gen_random_uuid(),
  checklist_id              uuid not null references checklists(id) on delete cascade,
  category                  text not null default 'General',
  item_text                 text not null,
  required_document_type_id uuid references document_templates(id) on delete set null,
  source_type               source_type not null default 'evidence',
  severity_weight           smallint not null default 1 check (severity_weight between 1 and 5),
  regulation_reference      text,
  guidance_notes            text,
  sort_order                integer not null default 0
);

-- --- Reusable content library (hybrid dynamic-assembly model) --------
create table hazard_library (
  id                   uuid primary key default gen_random_uuid(),
  activity             text not null,
  hazard               text not null,
  who_may_be_harmed    text,
  standard_controls    text not null,
  default_a            smallint not null default 1,   -- likelihood factors A x B x C x D = R
  default_b            smallint not null default 1,
  default_c            smallint not null default 1,
  default_d            smallint not null default 1,
  regulation_reference text,
  active               boolean not null default true,
  created_by           uuid references profiles(id) on delete set null,
  created_at           timestamptz not null default now()
);

create table hazard_library_sectors (
  hazard_library_id uuid not null references hazard_library(id) on delete cascade,
  sector_id         uuid not null references sectors(id) on delete cascade,
  primary key (hazard_library_id, sector_id)
);

create table method_step_library (
  id                     uuid primary key default gen_random_uuid(),
  activity_type          text not null,
  step_description        text not null,
  key_hazards_controls    text,
  responsible_role_default text,
  sort_hint              integer not null default 0,
  active                 boolean not null default true,
  created_by             uuid references profiles(id) on delete set null,
  created_at             timestamptz not null default now()
);

create table method_step_library_sectors (
  method_step_library_id uuid not null references method_step_library(id) on delete cascade,
  sector_id              uuid not null references sectors(id) on delete cascade,
  primary key (method_step_library_id, sector_id)
);

-- Flagged gaps: a questionnaire scenario the library did not cover well.
-- Once drafted & approved these become permanent library entries (the core scaling loop).
create table library_gap_flags (
  id          uuid primary key default gen_random_uuid(),
  kind        text not null check (kind in ('hazard', 'method_step')),
  sector_id   uuid references sectors(id) on delete set null,
  context     text not null,                 -- what the questionnaire described
  proposed    jsonb,                          -- staff's draft entry
  status      text not null default 'open' check (status in ('open', 'drafted', 'approved', 'dismissed')),
  resolved_library_id uuid,                   -- id of the created library row once approved
  created_by  uuid references profiles(id) on delete set null,
  created_at  timestamptz not null default now()
);

-- --- Audits --------------------------------------------------------
create table audits (
  id                uuid primary key default gen_random_uuid(),
  client_id         uuid not null references clients(id) on delete cascade,
  checklist_id      uuid not null references checklists(id) on delete restrict,
  uploaded_file_url text,
  status            audit_status not null default 'in_progress',
  overall_score     numeric(5,2),            -- 0-100, computed from CONFIRMED results only
  audited_by        uuid references profiles(id) on delete set null,
  audit_date        date not null default current_date,
  created_at        timestamptz not null default now()
);

create table audit_results (
  id                 uuid primary key default gen_random_uuid(),
  audit_id           uuid not null references audits(id) on delete cascade,
  checklist_item_id  uuid not null references checklist_items(id) on delete restrict,
  status             audit_result_status,          -- NULL = not yet reviewed by a human
  ai_suggested_status audit_result_status,         -- AI hint only; never counts until confirmed
  ai_rationale       text,
  reviewer_notes     text,
  evidence_page_ref  text,
  action_required    text,
  reviewed_by        uuid references profiles(id) on delete set null,
  reviewed_at        timestamptz,
  unique (audit_id, checklist_item_id)
);

-- --- Evidence documents (third-party issued; IMPI files, never authors) --
create table evidence_documents (
  id                uuid primary key default gen_random_uuid(),
  client_id         uuid not null references clients(id) on delete cascade,
  checklist_item_id uuid references checklist_items(id) on delete set null,
  audit_id          uuid references audits(id) on delete set null,
  document_ref      text unique,             -- IMPI-EVD-... auto (trigger)
  doc_year          int,
  seq               int,
  title             text,
  file_url          text,
  issuing_body      text,
  certificate_number text,
  issue_date        date,
  expiry_date       date,                    -- drives future audit re-flagging when lapsed
  status            evidence_status not null default 'pending_review',
  reviewed_by       uuid references profiles(id) on delete set null,
  uploaded_by       uuid references profiles(id) on delete set null,
  created_at        timestamptz not null default now()
);

-- --- Generated documents (IMPI-authored; each revision is a new immutable row) --
create table generated_documents (
  id                   uuid primary key default gen_random_uuid(),
  client_id            uuid not null references clients(id) on delete cascade,
  document_template_id uuid not null references document_templates(id) on delete restrict,
  audit_id             uuid references audits(id) on delete set null,
  questionnaire_response_id uuid,
  parent_document_id   uuid references generated_documents(id) on delete set null,  -- set when this is a revision
  document_ref         text unique,          -- IMPI-<TYPE>-<CODE>-<YEAR>-<SEQ>-Rev<N> auto (trigger)
  doc_year             int,
  seq                  int,
  revision             int not null default 1,
  title                text,
  site_project_name    text,
  prepared_by_name     text,
  reviewed_by_name     text,
  approved_by_name     text,
  revision_date        date,
  file_url             text,                 -- .docx produced by the generator
  pdf_url              text,                 -- PDF rendition used for final assembly (see DECISIONS.md item 4)
  status               generated_status not null default 'draft',
  generated_by         uuid references profiles(id) on delete set null,
  generated_at         timestamptz not null default now()
);

create index on generated_documents (client_id, document_template_id);
create index on evidence_documents (client_id);
create index on audit_results (audit_id);

-- --- Questionnaire responses (feed document generation) --------------
create table questionnaire_responses (
  id                   uuid primary key default gen_random_uuid(),
  client_id            uuid not null references clients(id) on delete cascade,
  document_template_id uuid not null references document_templates(id) on delete restrict,
  audit_id             uuid references audits(id) on delete set null,
  responses            jsonb not null default '{}'::jsonb,
  created_by           uuid references profiles(id) on delete set null,
  created_at           timestamptz not null default now()
);

alter table generated_documents
  add constraint generated_documents_qr_fk
  foreign key (questionnaire_response_id) references questionnaire_responses(id) on delete set null;

-- --- Final assembled safety files ----------------------------------
create table safety_files (
  id                   uuid primary key default gen_random_uuid(),
  client_id            uuid not null references clients(id) on delete cascade,
  document_ref         text unique,          -- IMPI-SF-... auto (trigger)
  doc_year             int,
  seq                  int,
  title                text,
  site_project_name    text,
  included_document_ids jsonb not null default '[]'::jsonb,  -- ordered [{kind:'generated'|'evidence', id, toc_title}]
  final_pdf_url        text,
  compiled_by          uuid references profiles(id) on delete set null,
  compiled_at          timestamptz not null default now()
);

-- --- Numbering counter (per client + type + year) -----------------
create table document_counters (
  client_id uuid not null references clients(id) on delete cascade,
  type_code text not null,
  year      int  not null,
  last_seq  int  not null default 0,
  primary key (client_id, type_code, year)
);

-- --- Document Control Register (derived view; never entered directly) --
create view document_control_register as
  select
    g.document_ref,
    coalesce(g.title, dt.name)               as document_title,
    'generated'::source_type                 as source_type,
    g.revision,
    g.client_id,
    coalesce(g.prepared_by_name, '')         as prepared_by,
    coalesce(g.reviewed_by_name, '')         as reviewed_by,
    coalesce(g.approved_by_name, '')         as approved_by,
    g.status::text                           as status,
    coalesce(g.revision_date, g.generated_at::date) as doc_date
  from generated_documents g
  join document_templates dt on dt.id = g.document_template_id
  union all
  select
    e.document_ref,
    coalesce(e.title, e.issuing_body, 'Evidence document'),
    'evidence'::source_type,
    null::int,
    e.client_id,
    coalesce(e.issuing_body, '')             as prepared_by,
    ''                                       as reviewed_by,
    ''                                       as approved_by,
    e.status::text,
    e.issue_date
  from evidence_documents e;
